function [Hd, order] = filter_lowpass
%FILTER_LOWPASS2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 11-Apr-2023 01:05:24
% Order 334

% Generalized REMEZ FIR Lowpass filter designed using the FIRGR function.

% All frequency values are in Hz.
Fs = 31249.994261;  % Sampling Frequency

Fpass = 500;             % Passband Frequency
Fstop = 700;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 30;              % Density Factor
order = 334;

% Calculate the coefficients using the FIRGR function.
b  = firgr('mineven', [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Dpass ...
           Dstop], {dens});
Hd = dfilt.dffir(b);

% [EOF]

% %% f = logspace(log10(Fpass), log10(Fs/2), N);
% % построение АЧХ и ФЧХ
% [h, w] = freqz(b);
% freq = w / (2 * pi) * Fs;
% magnitude = 20 * log10(abs(h));
% phase = unwrap(angle(h)) * 180 / pi;
% 
% % построение графика
% figure;
% subplot(2, 1, 1);
% plot(freq, magnitude);
% title('АЧХ');
% xlabel('Частота, Гц');
% ylabel('Амплитуда, дБ');
% grid on;
% 
% subplot(2, 1, 2);
% plot(freq, phase);
% title('ФЧХ');
% xlabel('Частота, Гц');
% ylabel('Фаза, градусы');
% grid on;